import { ReduxProviders } from '@/redux/Providers'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from './providers/theme-provider'
import { Toaster } from '@/components/ui/toaster'
import localFont from 'next/font/local'
import ReactQueryProvider from './providers/ReactQueryProvider'
import Navbar from '@/components/nav/Navbar'
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })
const primaryFont = localFont({
  src: '../public/fonts/FarsiFont.woff2',
  variable: '--font-sans',
})
const numericFont = localFont({
  src: '../public/fonts/FarsiAdad.woff2',
  variable: '--font-adad',
})
const numericBoldFont = localFont({
  src: '../public/fonts/FarsiAdad-Bold.woff2',
  variable: '--font-adad-bold',
})
const numericRegularFont = localFont({
  src: '../public/fonts/FarsiAdad-Regular.woff2',
  variable: '--font-adad-reg',
})
export const metadata: Metadata = {
  title: 'e-shop',
  description: 'Generated by Saeid',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body
        className={`${primaryFont.variable} font-farsi adad  antialiased  `}
      >
        <ReduxProviders>
          <ReactQueryProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <Toaster />
              <div className="flex flex-col min-h-screen">
                <Navbar />
                <main className="flex-grow relative ">
                  <div className="-z-50 absolute h-full w-full bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] [background-size:16px_16px] [mask-image:radial-gradient(ellipse_50%_50%_at_50%_50%,#000_70%,transparent_100%)]"></div>
                  {children}
                </main>
                <Footer />
              </div>
            </ThemeProvider>
          </ReactQueryProvider>
        </ReduxProviders>
      </body>
    </html>
  )
}
